<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 14:00:39 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Najave Foruma';
$l['announcements'] = 'Najave';
$l['forum_announcement'] = 'Najave Foruma: {1}';
$l['error_invalidannouncement'] = 'Najava koju ste unijeli nije ispravna';
$l['announcement_edit'] = 'Uredi ovu najavu';
$l['announcement_qdelete'] = 'Izbriši ovu najavu';
$l['announcement_quickdelete_confirm'] = 'Jeste li sigurni da želite izbrisati ovu najavu?';
