<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 14:52:15 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Puna Verzija:';
$l['archive_replies'] = 'Odgovora';
$l['archive_reply'] = 'Odgovori';
$l['archive_pages'] = 'Stranica:';
$l['archive_note'] = 'Trenutno pregledavate \'svijetlu\' verziju foruma. <a href="{1}">Pogledajte punu verziju</a> sa odgovarajućim formatiranjem.';
$l['archive_nopermission'] = 'Žao nam je, ali nemate dopuštenje za pregled ovoga sadržaja.';
$l['error_nothreads'] = 'Trenutno nema tema u ovome forumu.';
$l['error_unapproved_thread'] = 'Ova tema nije odobrena. Molimo <a href="{1}">pogledajte punu verziju</a> za pregled sadržaja ove teme.';
$l['archive_not_found'] = 'Tražena stranica nije pronađena na ovom serveru.';
$l['error_mustlogin'] = 'Ovaj forum zahtjeva prijavu svih korisnika.';
