<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 14:53:55 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Niste unijeli ispravnu kombinaciju korisničkog imena i lozinke. <br /><br />Ako ste zaboravili svoju lozinku, molimo da  <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['logindata_invalidpwordusernameemail'] = 'Niste unijeli ispravnu kombinaciju e-maila i lozinke. <br /><br />Ako ste zaboravili svoju lozinku, molimo da  <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'Niste unijeli ispravnu kombinaciju e-maila i lozinke ili korisničkog imena i lozinke. <br /><br />Ako ste zaboravili svoju lozinku, molimo da  <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['logindata_regimageinvalid'] = 'Kod za potvrdu koji ste unijeli nije ispravan. Molimo unesite kod točno onako kakav je na slici.';
$l['logindata_regimagerequired'] = 'Molimo unesite kod za potvrdu kako biste nastavili s prijavom. Molimo unesite kod točno onako kakav je na slici.';
