<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 14:54:08 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Naslov vaše privatne poruke je predug. Molimo unesite kraći naslov.';
$l['pmdata_code_no_subject'] = '[Bez naslova]';
$l['pmdata_missing_subject'] = 'Niste unijeli naslov za vašu poruku. Molimo unesite naslov.';
$l['pmdata_missing_message'] = 'Niste napisali poruku za slanje. Molimo upišite poruku.';
$l['pmdata_invalid_recipients'] = 'Jedan ili više primatelja koje ste izabrali nisu registrirana korisnička imena. Neispravni primatelji: {1}';
$l['pmdata_no_recipients'] = 'Niste unijeli niti jednog primatelja za slanje ove poruke. Trebate unijeti bar jedno korisničko ime u polje \'za\'.';
$l['pmdata_too_many_recipients'] = 'Dozvoljeno vam je slanje poruka samo {1} korisnika istovremeno.';
$l['pmdata_recipient_is_ignoring'] = 'Ne možete slati poruke za {1} jer ste na njegovom popisu za ignoriranje.';
$l['pmdata_recipient_has_buddy_only'] = 'Ne možete slati poruke za {1} jer niste na njegovom popisu na prijatelja.';
$l['pmdata_recipient_pms_disabled'] = '{1} je onemogućio privatne poruke. Ne možete poslati privatnu poruku ovom korisniku.';
$l['pmdata_recipient_reached_quota'] = '{1} ima pun sandučić za privatne poruke te mu vaša poruka ne može biti poslana.';
$l['pmdata_pm_flooding'] = 'Prebrzo pokušavate poslati poruku nakon slanja prethodne poruke. Molimo vas pričekajte još {1} sekundi.';
$l['pmdata_pm_flooding_one_second'] = 'Prebrzo pokušavate poslati poruku nakon slanja prethodne poruke. Molimo vas pričekajte još 1 sekundu.';
