<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 14:54:53 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Niste unijeli korisničko ime. Molimo vas da ga uneste.';
$l['userdata_banned_username'] = 'Ne možete se registrirati s izabranim korisničkim imenom. Molimo vas da odaberete neko drugo.';
$l['userdata_bad_characters_username'] = 'Upisano korisničko ime sadrži nedozvoljene znakove. Molimo vas da odaberete neko drugo.';
$l['userdata_invalid_username_length'] = 'Uneseno korisničko ime je neodgovarajuće dužine. Molimo unesite korisničko ime između {1} i {2} znakova.';
$l['userdata_invalid_usertitle_length'] = 'Vlastiti korisnički naziv koji ste unijeli nije ispravne dužine. Molimo unesite naziv kraći od {1} znakova.';
$l['userdata_username_exists'] = 'Korisničko ime koje ste unijeli već postoji. Molimo vas da izaberete drugo korisničko ime.';
$l['userdata_invalid_password_length'] = 'Upisana lozinka nije odgovarajuće dužine. Molimo unesite lozinku između {1} i {2} znakova.';
$l['userdata_no_complex_characters'] = 'Lozinka koju ste upisali nije dovoljno složena. Molimo unesite lozinku koja je bar {1} znakova dugačka, i sadrži bar jedno: veliko slovo, malo slovo i broj.';
$l['userdata_passwords_dont_match'] = 'Potvrđena lozinka se ne poklapa sa izvornom. Molimo potvrdite vašu lozinku ispravno.';
$l['userdata_bad_password_security'] = 'Lozinka koju ste unijeli se podudara s vašim korisničkim imenom ili e-mailom. Molimo unesite jaču lozinku.';
$l['userdata_missing_email'] = 'Niste unijeli e-mail adresu. Molimo unesite e-mail.';
$l['userdata_invalid_email_format'] = 'Unesena e-mail adresa nije ispravna. Molimo unesite ispravnu e-mail adresu.';
$l['userdata_emails_dont_match'] = 'Potvrđena e-mail adresa se ne poklapa sa izvornom. Molimo potvrdite vašu e-mail adresu ispravno.';
$l['userdata_banned_email'] = 'Unesena e-mail adresa trenutno nije dozvoljena. Molimo unesite drugu e-mail adresu.';
$l['userdata_email_already_in_use'] = 'Unijeli ste e-mail adresu koju već koristi neki drugi član na ovome forummu. Molimo unesite drugu e-mail adresu.';
$l['userdata_dob_required'] = 'Niste izabrali vaš datum rođenja. Molimo izaberite vaš datum rođenja za nastavak - kasnije možete sakriti vaš rođendan i godine od drugih korisnika.';
$l['userdata_invalid_website'] = 'Unesena adresa web stranice nije ispravna. Molimo unesite ispravnu adresu ili ostavite prazno polje.';
$l['userdata_invalid_icq_number'] = 'Uneseni ICQ broj nije ispravan. Molimo unesite ispravan ICQ broj ili ostavite prazno polje.';
$l['userdata_invalid_birthday'] = 'Uneseni rođendan nije ispravan. Molimo unesite rođendan ispravno ili ostavite prazno polje.';
$l['userdata_invalid_birthday_coppa'] = 'Za potvrdu vaših godina, molimo vas, unesite godinu rođenja. Možete sakriti vaše godine i datum rođenja u postavkama vašeg profila.';
$l['userdata_invalid_birthday_coppa2'] = 'Morate imati bar 13 godina da biste postali član ovog foruma. Molimo kontaktirajte administratora.';
$l['userdata_invalid_birthday_privacy'] = 'Molimo izaberite ispravnu ponudu privatnosti za rođendan.';
$l['userdata_invalid_referrer'] = 'Uneseni preporučitelj ne postoji. Molimo unesite preporučitelja koji postoji ili ostavite prazno polje.';
$l['userdata_invalid_language'] = 'Jezik koji ste izabrali ne postoji. Molimo izaberite postojeći.';
$l['userdata_missing_returndate'] = 'Određenom datumu povratka nedostaje jedno ili više polja. Molimo provjerite jeste li popunili polja za dan, mjesec, i godinu.';
$l['userdata_missing_required_profile_field'] = 'Niste upisali ništa u polje "{1}". Molimo upišite ili odaberite vrijednost za ovo polje.';
$l['userdata_bad_profile_field_value'] = 'Niste unijeli ispravnu vrijednost polja "{1}". Molimo unesite ispravnu vrijednost prije nastavka.';
$l['userdata_bad_profile_field_values'] = 'Niste odabrali ispravnu mogućnost polja "{1}". Molimo odaberite mogućnost s ponuđenog popisa.';
$l['userdata_max_limit_reached'] = 'Unijeli ste neispravan broj znakova polja "{1}". Molimo popunite ovo polje sa manje od {2} znakova.';
$l['userdata_invalid_checkfield'] = 'Otkrili smo da je ovaj obrazac popunio spam robot. Ako je to pogreška, molimo vas da kontaktirate administratora foruma.';
$l['userdata_invalid_postnum'] = 'Broj poruka koji ste unijeli nije ispravan. Molimo unesite ispravan broj poruka, ili ostavite prazno polje.';
$l['userdata_invalid_threadnum'] = 'Broj tema koji ste unijeli nije ispravan. Molimo unesite ispravan broj tema, ili ostavite prazno polje.';
