<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 15:00:35 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Pozdrav svijete!';
$l['hello_add'] = 'Dodaj';
$l['hello_add_message'] = 'Dodaj poruku';
$l['hello_empty'] = 'Poruke nisu pronađene.';
$l['hello_message_empty'] = 'Poruka ne može biti prazna.';
$l['hello_done'] = 'Uspiješno dodana nova poruka';
