<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 15:00:54 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'User Maintenance';
$l['s1_desc'] = 'Basic instructions for maintaining a forum account.';
$l['s2_name'] = 'Pisanje';
$l['s2_desc'] = 'Pisanje, odgovaranje i osnovno korištenje foruma.';
