<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 15:57:57 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Hvala vam, tema je uspješno ocjenjena. Sada ćete biti vraćeni na temu.';
$l['error_invalidrating'] = 'Izabrali ste neispravnu ocjenu za ovu temu. molimo vas da se vratite natrag i pokušate ponovno.';
$l['error_alreadyratedthread'] = 'Žao nam je, već ste ocijenili ovu temu.';
$l['error_cannotrateownthread'] = 'Žao nam je, ne možete ovjenjivati vašu temu.';
$l['rating_votes_average'] = '{1} Glas(ova) - {2} od 5 u prosjeku';
$l['one_star'] = '1 zvijezda od 5';
$l['two_stars'] = '2 zvijezda od 5';
$l['three_stars'] = '3 zvijezda od 5';
$l['four_stars'] = '4 zvijezda od 5';
$l['five_stars'] = '5 zvijezda od 5';
$l['rating_added'] = 'Vaša ocjena je dodana!';
