<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://www.ikerepc.tk/
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Thu, 12 Mar 2015 15:10:54 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Pošalji temu prijatelju';
$l['send_thread'] = 'Pošalji prijatelju';
$l['recipient'] = 'Primatelj:';
$l['recipient_note'] = 'Unesite prijateljev e-mail ovdje.';
$l['subject'] = 'Naslov:';
$l['message'] = 'Poruka:';
$l['error_nosubject'] = 'Trebate unijeti naslov kako biste poslali temu prijatelju.';
$l['error_nomessage'] = 'Trebate unijeti poruku kako biste poslali ovu temu prijatelju.';
