<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:08:54 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Osoblje foruma';
$l['forum_team'] = 'Osoblje foruma';
$l['moderators'] = 'Moderatori';
$l['username'] = 'Korisničko ime';
$l['lastvisit'] = 'Zadnja posjeta';
$l['email'] = 'E-mail';
$l['pm'] = 'PP';
$l['mod_forums'] = 'Forum(i)';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['group_leaders'] = 'Voditelj(i)';
$l['group_members'] = 'Član(ovi)';
$l['no_members'] = 'Nema članova u ovoj grupi';
$l['error_noteamstoshow'] = 'Ovdje nema osoblja za prikaz';
$l['away'] = 'Odsutan';
